# **Group Project 9**

## Social Media Sentiment analysis 

# Team Members
## Duygu 8815048
## Varun 8894799
## Rohit 8895806

## **Getting data from Reddit**

In [1]:
import praw
import pandas as pd
# Reddit API credentials
CLIENT_ID = "QhxM4QaIZxn2yIxdOByVOA"
CLIENT_SECRET = "J0eBuxj7AM5yev0qzlaxZf9O3Mr9ZA"
# Initialize the Reddit API client
reddit = praw.Reddit(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    user_agent=True,
)
def get_posts(subreddit, count=10):
    subreddit = reddit.subreddit(subreddit)
    posts = subreddit.hot(limit=count)
    post_data = {
        "Title": [],
        "Author": [],
        "Score": [],
        "Full Text": [],
        "URL": [],
    }
    for post in posts:
        post_data["Title"].append(post.title)
        post_data["Author"].append(str(post.author))
        post_data["Score"].append(post.score)
        post_data["Full Text"].append(post.selftext)
        post_data["URL"].append(post.url)

    df = pd.DataFrame(post_data)
    return df

post_count = 1000  # Number of posts to fetch

## **Getting data with respect to data topics**
### US POLITICS

In [2]:
df_trump = get_posts('trumptweets', post_count)
df_trump.shape

(997, 5)

In [3]:
uspolitics = get_posts('uspolitics', post_count)
uspolitics.shape

(931, 5)

In [4]:
kamalaharris = get_posts("kamalaharris", post_count)

joebiden = get_posts("joebiden", post_count)

democraticparty = get_posts("democraticparty", post_count)

billclinton = get_posts("billclinton", post_count)


## Getting raw text data from Reddit

In [5]:

data = pd.concat([kamalaharris,joebiden,democraticparty,billclinton,uspolitics,df_trump], ignore_index=True)
data.head()
data.to_csv('us_elections.csv')

## Hugging face pre-trained model for ground truth labelling 

In [7]:
import pandas as pd
from transformers import pipeline

# Extracting the Title column from the data
texts = data['Title'].tolist()

# Load the sentiment analysis pipeline with the BERTweet model
model_name = "finiteautomata/bertweet-base-sentiment-analysis"
sentiment_analyzer = pipeline("sentiment-analysis", model=model_name)

# Use the sentiment analysis pipeline to label the text data
results = sentiment_analyzer(texts)

d:\Assignments\Fundamental of AAIML\Assignemnt week 2\CSCN8010\venv\tensorflow_cpu\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

All the layers of TFRobertaForSequenceClassification were initialized from the model checkpoint at finiteautomata/bertweet-base-sentiment-analysis.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForSequenceClassification for predictions without further training.
emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0


## Mapping of Sentiments

In [1]:
label_mapping = {
    'POS': "Postive",
    'NEU': "Neutral",
    'NEG': "Negative"
}  

data['sentiment_label'] = [label_mapping[result['label']] for result in results]
data['confidence_score'] = [result['score'] for result in results]

NameError: name 'results' is not defined

## Cheking for class balance in the target feature

In [9]:
data['sentiment_label'].value_counts()

sentiment_label
Neutral     2208
Negative    1108
Postive      373
Name: count, dtype: int64

## Getting mapped labelled data to csv for processing and analysis

In [10]:
data.to_csv('us_polotics_sentiment_confidence.csv', index=False)

## emojis collection

In [1]:
emojis_with_feelings = [
    ("😊", "happy"),
    ("❤️", "love"),
    ("😢", "sad"),
    ("😂", "laughing"),
    ("😍", "admiration"),
    ("😎", "cool"),
    ("😭", "crying"),
    ("😡", "angry"),
    ("😴", "sleepy"),
    ("🤔", "confused"),
    ("😌", "relieved"),
    ("😋", "delicious"),
    ("😒", "unamused"),
    ("🤗", "hugging"),
    ("😟", "worried"),
    ("😇", "angelic"),
    ("😖", "frustrated"),
    ("🙄", "annoyed"),
    ("😨", "scared"),
    ("🥰", "loving"),
    ("🥺", "pleading"),
    ("😵", "dizzy"),
    ("😈", "mischievous"),
    ("😳", "embarrassed"),
    ("🤢", "nauseated"),
    ("😑", "expressionless"),
    ("😓", "anxious"),
    ("😔", "pensive"),
    ("🥳", "celebrating"),
    ("😬", "grimacing"),
    ("😐", "neutral"),
    ("😕", "confused"),
    ("😞", "disappointed"),
    ("😲", "astonished"),
    ("🤫", "shushing"),
    ("😪", "sleepy"),
    ("🤥", "lying"),
    ("😖", "conflicted"),
    ("🤡", "clownish"),
    ("😭", "sobbing"),
    ("🤧", "sneezing"),
    ("🤣", "rolling on the floor laughing"),
    ("🙃", "upside-down"),
    ("🤯", "mind-blown"),
    ("🥱", "yawning"),
    ("😤", "exasperated"),
    ("😮‍💨", "mind-blown"),
    ("🥲", "teary-eyed"),
    ("🥵", "hot"),
    ("🥶", "cold"),
    ("😴", "sleepy"),
    ("🤔", "pondering"),
    ("🥴", "woozy"),
    ("😬", "grimacing"),
    ("🤢", "nauseous"),
    ("🤐", "zipped lips"),
    ("🤕", "hurt"),
    ("🥳", "celebrating"),
    ("😈", "mischievous"),
    ("😖", "frustrated"),
    ("🤪", "crazy"),
    ("🤤", "drooling"),
    ("🤮", "vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "cursing"),
    ("🥺", "begging"),
    ("🥱", "yawning"),
    ("🥳", "partying"),
    ("🥰", "blissful"),
    ("🥵", "overheated"),
    ("🥶", "freezing"),
    ("🤠", "cowboy"),
    ("🤑", "money-mouth"),
    ("🤓", "nerdy"),
    ("🤗", "hugging"),
    ("🤡", "clown"),
    ("🤥", "liar"),
    ("🤫", "shushing"),
    ("🤬", "angry"),
    ("🤯", "mind-blown"),
    ("🧐", "inquiring"),
    ("🤪", "zany"),
    ("🤩", "excited"),
    ("🤔", "thoughtful"),
    ("🤨", "skeptical"),
    ("🤫", "quiet"),
    ("🧐", "curious"),
    ("🤪", "wacky"),
    ("🤩", "wonderful"),
    ("🤗", "friendly"),
    ("🤬", "furious"),
    ("🤯", "astounding"),
    ("🧐", "inspecting"),
    ("🤓", "bookish"),
    ("🤨", "questioning"),
    ("🤫", "silent"),
    ("🧐", "analyzing"),
    ("🤪", "crazy"),
    ("🤩", "fantastic"),
    ("🤔", "pondering"),
    ("🤨", "doubting"),
    ("🤫", "hushed"),
    ("🤐", "mute"),
    ("🤨", "inquisitive"),
    ("🤓", "geeky"),
    ("🤗", "hug"),
    ("🤖", "robotic"),
    ("🤧", "sneezing"),
    ("🤣", "ROFL"),
    ("🤡", "clown"),
    ("🤢", "sick"),
    ("🤐", "zip-it"),
    ("🤕", "ouch"),
    ("🥳", "party"),
    ("😈", "devilish"),
    ("😖", "upset"),
    ("🤪", "silly"),
    ("🤤", "hungry"),
    ("🤮", "disgust"),
    ("🤩", "amazed"),
    ("🤬", "angry"),
    ("🥺", "pleading"),
    ("🥱", "tired"),
    ("🥳", "celebration"),
    ("🥰", "adoration"),
    ("🥵", "hot"),
    ("🥶", "cold"),
    ("🤠", "cowboy"),
    ("🤑", "money"),
    ("🤓", "nerd"),
    ("🤗", "warm"),
    ("🤡", "fool"),
    ("🤥", "lie"),
    ("🤫", "shh"),
    ("🤬", "rage"),
    ("🤯", "explode"),
    ("🧐", "detective"),
    ("🤪", "goofy"),
    ("🤩", "excite"),
    ("🤔", "think"),
    ("🤨", "suspicious"),
    ("🤫", "quiet"),
    ("🧐", "observe"),
    ("🤪", "crazy"),
    ("🤩", "amazing"),
    ("🤗", "embrace"),
    ("🤬", "angry"),
    ("🤯", "unbelievable"),
    ("🧐", "inspect"),
    ("🤓", "knowledge"),
    ("🤨", "doubt"),
    ("🤫", "silent"),
    ("🧐", "examine"),
    ("🤪", "wacky"),
    ("🤩", "awesome"),
    ("🤔", "ponder"),
    ("🤨", "mistrust"),
    ("🤫", "hush"),
    ("🤐", "mute"),
    ("🤨", "curious"),
    ("🤓", "studious"),
    ("🤗", "hug"),
    ("🤖", "robot"),
    ("🤧", "sneeze"),
    ("🤣", "laugh"),
    ("🤡", "jester"),
    ("🤢", "nausea"),
    ("🤐", "silence"),
    ("🤕", "injured"),
    ("🥳", "festive"),
    ("😈", "devil"),
    ("😖", "distressed"),
    ("🤪", "eccentric"),
    ("🤤", "mouth-watering"),
    ("🤮", "disgusted"),
    ("🤩", "awe"),
    ("🤬", "outraged"),
    ("🥺", "plead"),
    ("🥱", "yawn"),
    ("🥳", "celebrate"),
    ("🥰", "bliss"),
    ("🥵", "overheated"),
    ("🥶", "freezing"),
    ("🤠", "wild west"),
    ("🤑", "wealth"),
    ("🤓", "intellectual"),
    ("🤗", "affection"),
    ("🤡", "comical"),
    ("🤥", "dishonest"),
    ("🤫", "quietness"),
    ("🤬", "wrath"),
    ("🤯", "mind blown"),
    ("🧐", "scrutinize"),
    ("🤪", "offbeat"),
    ("🤩", "fantastical"),
    ("🤔", "reflective"),
    ("🤨", "distrustful"),
    ("🤫", "hushed"),
    ("🧐", "inquisitive"),
    ("🤪", "madcap"),
    ("🤩", "awe-inspiring"),
    ("🤗", "cordial"),
    ("🤬", "fury"),
    ("🤯", "astounded"),
    ("🧐", "inspect"),
    ("🤓", "studious"),
    ("🤨", "disbelief"),
    ("🤫", "quietude"),
    ("🧐", "scrutinize"),
    ("🤪", "zany"),
    ("🤩", "marvelous"),
    ("🤔", "thoughtful"),
    ("🤨", "dubious"),
    ("🤫", "hush"),
    ("🤐", "sealed lips"),
    ("🤨", "inquisitive"),
    ("🤓", "intellect"),
    ("🤗", "warm embrace"),
    ("🤖", "robot"),
    ("🤧", "achoo"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "green face"),
    ("🤐", "zipped mouth"),
    ("🤕", "bandaged head"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "crazy face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with raised eyebrow"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
    ("🤩", "star-struck"),
    ("🤬", "face with symbols on mouth"),
    ("🥺", "pleading face"),
    ("🥱", "yawning face"),
    ("🥳", "partying face"),
    ("🥰", "smiling face with hearts"),
    ("🥵", "hot face"),
    ("🥶", "cold face"),
    ("🤠", "cowboy hat face"),
    ("🤑", "money-mouth face"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤡", "clown face"),
    ("🤥", "lying face"),
    ("🤫", "shushing face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤗", "hugging face"),
    ("🤬", "angry face"),
    ("🤯", "exploding head"),
    ("🧐", "face with monocle"),
    ("🤓", "nerd face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🧐", "face with monocle"),
    ("🤪", "crazy face"),
    ("🤩", "star-struck"),
    ("🤔", "thinking face"),
    ("🤨", "face with raised eyebrow"),
    ("🤫", "shushing face"),
    ("🤐", "zipper-mouth face"),
    ("🤨", "face with raised eyebrow"),
    ("🤓", "nerd face"),
    ("🤗", "hugging face"),
    ("🤖", "robot face"),
    ("🤧", "sneezing face"),
    ("🤣", "rolling on the floor laughing"),
    ("🤡", "clown face"),
    ("🤢", "nauseated face"),
    ("🤐", "zipper-mouth face"),
    ("🤕", "face with head-bandage"),
    ("🥳", "partying face"),
    ("😈", "smiling face with horns"),
    ("😖", "confounded face"),
    ("🤪", "zany face"),
    ("🤤", "drooling face"),
    ("🤮", "face vomiting"),
]


In [12]:
#!pip install textblob

In [13]:
#pip install slang

## Text processing function for emojis handling, slang handling, punctuation, stop-words, hashtags and Lemmatization

In [2]:
import string
import re
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import re
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# Custom slang dictionary
slang_dict = {
    "lol": "laugh out loud",
    "btw": "by the way",
    "omg": "oh my god",
    "thx": "thanks",
    "np": "no problem",
    "b4": "before",
    "gr8": "great",
    "u": "you",
    "r": "are",
    "ur": "your",
    "w8": "wait",
    "pls": "please",
    "bday": "birthday",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "ttyl": "talk to you later",
    "bff": "best friend forever",
    "idk": "I don't know",
    "np": "no problem",
    "ty": "thank you",
    "yw": "you're welcome",
    "afk": "away from keyboard",
    "brb": "be right back",
    "gg": "good game",
    "g2g": "got to go",
    "hmu": "hit me up",
    "jk": "just kidding",
    "omw": "on my way",
    "otp": "on the phone",
    "tmi": "too much information",
    "wb": "welcome back",
    "yw": "you're welcome",
    "bae": "before anyone else",
    "fomo": "fear of missing out",
    "ftw": "for the win",
    "irl": "in real life",
    "nvm": "never mind",
    "srsly": "seriously",
    "tgif": "thank goodness it's Friday",
    "wfh": "work from home",
}


def handle_emojis_with_lemmatizer1(text):
    # Converting emojis to their emotional descriptions
    for emoji_char, emoji_description in emojis_with_feelings:
        text = text.replace(emoji_char, " " + emoji_description)

    # Convert text to lowercase
    text = text.lower()

    # Remove hashtags using regex
    pattern = r'#\w+'
    text = re.sub(pattern, '', text)

    # Handle slang words using the custom slang dictionary
    words = word_tokenize(text)
    words_with_slang_replaced = [slang_dict[word] if word in slang_dict else word for word in words]
    text = " ".join(words_with_slang_replaced)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize the text into words
    words = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words("english"))
    words_without_stopwords = [word for word in words if word not in stop_words]

    # Lemmatize the tokens
    blob = TextBlob(" ".join(words_without_stopwords))
    lemmatized_words = [word.lemmatize() for word in blob.words]

    # Reconstructing the text with lemmatized words
    lemmatized_text_with_emojis = " ".join(lemmatized_words)
    for emoji_description, emoji_char in emojis_with_feelings:
        lemmatized_text_with_emojis = lemmatized_text_with_emojis.replace(emoji_description, emoji_char)

    return lemmatized_text_with_emojis

# Sa,ple test case
emojis_with_feelings = [("😊", "happy"), ("😢", "sad"), ("😄", "joyful")]
text = "This is a sample text with #hashtag and emojis 😊😢😄. lol btw omg"

preprocessed_text = handle_emojis_with_lemmatizer1(text)
print(preprocessed_text)


sample text emojis happy sad joyful laugh loud way oh god


## Loading the labelled dataset and applying the above created preprocessing function

In [3]:
import pandas as pd

df_new = pd.read_csv('us_polotics_sentiment_confidence.csv')

df_new['preprocessed_text'] = df_new['Title'].apply(handle_emojis_with_lemmatizer1)

In [16]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: gensim in d:\assignments\fundamental of aaiml\assignemnt week 2\cscn8010\venv\tensorflow_cpu\lib\site-packages (4.3.1)




[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Word 2 Vec

In [4]:
import pandas as pd
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

In [5]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
from nltk.tokenize import sent_tokenize, word_tokenize

preprocessed_texts = df_new['preprocessed_text'].tolist()

sentence_tokens = [sent_tokenize(text) for text in preprocessed_texts]

all_words = [word for tokens in sentence_tokens for word in word_tokenize(" ".join(tokens))]

# Load or train a Word2Vec model on your preprocessed text
word2vec_model = Word2Vec(sentences=[all_words], vector_size=100, window=5, min_count=1, sg=0)

sentence_vectors = []

for tokens in sentence_tokens:
    word_vectors = [word2vec_model.wv[word] for word in word_tokenize(" ".join(tokens)) if word in word2vec_model.wv]

    if len(word_vectors) > 0:
        sentence_vector = np.mean(word_vectors, axis=0)
    else:
        sentence_vector = np.zeros(word2vec_model.vector_size)
    sentence_vectors.append(sentence_vector)

sentence_vectors_array = np.array(sentence_vectors)


In [19]:
X_word_2_vec = sentence_vectors_array

## Creating a dataframe consisting word 2 Vec representation

In [20]:
df_word_2_vec = pd.DataFrame(X_word_2_vec)

## Adding the dependent feature 'sentiments' to the data frame

In [21]:
df_word_2_vec['sentiments'] = df_new['sentiment_label']

In [22]:
df_word_2_vec

0         1         2         3         4         5         6  \
0    -0.000418  0.027125  0.021528  0.011896 -0.011664 -0.010974 -0.010930   
1    -0.003194  0.024958  0.019977  0.012267 -0.011787 -0.009225 -0.007830   
2    -0.003045  0.018391  0.017880  0.009451 -0.010769 -0.006018 -0.007702   
3    -0.001312  0.021969  0.018271  0.008554 -0.008873 -0.010274 -0.009320   
4    -0.000141  0.016063  0.014356  0.007500 -0.004554 -0.006702 -0.005220   
...        ...       ...       ...       ...       ...       ...       ...   
3684 -0.000656  0.003123  0.002424  0.002323  0.000265  0.001864  0.000564   
3685  0.001347  0.005754  0.002770  0.002099  0.001233 -0.000292  0.001007   
3686 -0.003247  0.000725 -0.001291  0.001829  0.000977  0.001396  0.001948   
3687 -0.003925  0.000800 -0.000181 -0.000889 -0.002131  0.000429 -0.004807   
3688 -0.003075  0.004307  0.008344  0.007030 -0.002150 -0.001391  0.000372   

             7         8         9  ...        91        92        93  \
0     0.023879 -0.014073  0.002420  ...  0.007013 -0.001046 -0.003721   
1     0.019383 -0.012400  0.005479  ...  0.005322  0.002225 -0.003774   
2     0.015567 -0.007238  0.005486  ...  0.003244  0.004433 -0.005191   
3     0.025276 -0.011471  0.002000  ...  0.004785  0.000035 -0.002028   
4     0.013989 -0.007935  0.000824  ...  0.002898  0.001020 -0.001930   
...        ...       ...       ...  ...       ...       ...       ...   
3684  0.000965 -0.001029 -0.000588  ...  0.002271  0.002686 -0.000179   
3685  0.003601 -0.003426  0.000524  ...  0.001175 -0.002695  0.001612   
3686  0.004477 -0.000583 -0.000388  ...  0.000908  0.001590 -0.001831   
3687  0.008512 -0.005782  0.002004  ...  0.003138 -0.002200 -0.002406   
3688  0.003044 -0.008764  0.006142  ...  0.005198  0.002486 -0.001081   

            94        95        96        97        98        99  sentiments  
0     0.013060  0.016309  0.004236  0.003606  0.006064  0.012041     Neutral  
1     0.012716  0.014896  0.005427  0.004365  0.003829  0.012512     Neutral  
2     0.007448  0.009034  0.003046  0.004493  0.001803  0.010924     Neutral  
3     0.012751  0.014262  0.002001  0.005669  0.003250  0.014472     Neutral  
4     0.007229  0.008826  0.003746  0.004330  0.003308  0.010147     Neutral  
...        ...       ...       ...       ...       ...       ...         ...  
3684  0.000351  0.002269 -0.001997 -0.000379  0.002756 -0.000485     Neutral  
3685  0.002959  0.002007 -0.000447 -0.000588  0.003323  0.002807     Neutral  
3686  0.004391 -0.002248  0.002438 -0.001717  0.001066  0.002862     Neutral  
3687  0.003787  0.008033 -0.003228 -0.000342  0.003000  0.003768     Neutral  
3688  0.006348  0.001238  0.003542 -0.000075  0.004691  0.003710     Neutral  

[3689 rows x 101 columns]

## Encoding the dependent feature

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df_word_2_vec["sentiments"] = encoder.fit_transform(df_word_2_vec["sentiments"])
df_word_2_vec.head()

0         1         2         3         4         5         6  \
0 -0.000418  0.027125  0.021528  0.011896 -0.011664 -0.010974 -0.010930   
1 -0.003194  0.024958  0.019977  0.012267 -0.011787 -0.009225 -0.007830   
2 -0.003045  0.018391  0.017880  0.009451 -0.010769 -0.006018 -0.007702   
3 -0.001312  0.021969  0.018271  0.008554 -0.008873 -0.010274 -0.009320   
4 -0.000141  0.016063  0.014356  0.007500 -0.004554 -0.006702 -0.005220   

          7         8         9  ...        91        92        93        94  \
0  0.023879 -0.014073  0.002420  ...  0.007013 -0.001046 -0.003721  0.013060   
1  0.019383 -0.012400  0.005479  ...  0.005322  0.002225 -0.003774  0.012716   
2  0.015567 -0.007238  0.005486  ...  0.003244  0.004433 -0.005191  0.007448   
3  0.025276 -0.011471  0.002000  ...  0.004785  0.000035 -0.002028  0.012751   
4  0.013989 -0.007935  0.000824  ...  0.002898  0.001020 -0.001930  0.007229   

         95        96        97        98        99  sentiments  
0  0.016309  0.004236  0.003606  0.006064  0.012041           1  
1  0.014896  0.005427  0.004365  0.003829  0.012512           1  
2  0.009034  0.003046  0.004493  0.001803  0.010924           1  
3  0.014262  0.002001  0.005669  0.003250  0.014472           1  
4  0.008826  0.003746  0.004330  0.003308  0.010147           1  

[5 rows x 101 columns]

## Splitting into dependent and independent set

In [24]:
X_word_2_vec = df_word_2_vec.iloc[:,:-1]
y_word_2_vec = df_word_2_vec.iloc[:,-1]

In [25]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled_w2_v, y_resampled_w2_v = smote.fit_resample(X_word_2_vec, y_word_2_vec)

## Train test split 

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled_w2_v, y_resampled_w2_v, test_size=0.2, random_state=42)

## Model fitting

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
classifier = rf.fit(X_train,y_train)

## Making prediction on test set

In [28]:
y_pred_rf1 = classifier.predict(X_test)

## Confusion Matrix, Accuracy, Precision and Recall and Cross validation 

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
from sklearn.model_selection import cross_val_score
cm_rf = confusion_matrix(y_test,y_pred_rf1)
print(cm_rf)
accuracy_score_rf1 = accuracy_score(y_test,y_pred_rf1)

acc_rf = accuracy_score(y_test,y_pred_rf1)
print("The accuracy of Random Forest Classifier using word2vec is", acc_rf)

precision_rf = precision_score(y_test, y_pred_rf1, average='macro')
print("The precision of Random Forest Classifier using word2vec is",precision_rf)
recall_rf = recall_score(y_test, y_pred_rf1, average='macro')
print("The recall of Random Forest Classifier using word2vec is ",recall_rf)

print("------------------------------------------------------------------")
scores_rf1 = cross_val_score(classifier,X_train,y_train,cv = 10, scoring = "accuracy")
print(scores_rf1)
print("-------------------------------------------------------------")
print("The mean cross validation accuracy is", scores_rf1.mean())

[[344  88   1]
 [ 95 339  26]
 [  8  10 414]]
The accuracy of Random Forest Classifier using word2vec is 0.8279245283018868
The precision of Random Forest Classifier using word2vec is 0.8280313871231638
The recall of Random Forest Classifier using word2vec is  0.8299157099664178
------------------------------------------------------------------
[0.79433962 0.83018868 0.78113208 0.81320755 0.81132075 0.81509434
 0.81886792 0.82075472 0.85471698 0.80907372]
-------------------------------------------------------------
The mean cross validation accuracy is 0.8148696365516997


## TFIDF

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X_tfidf = cv.fit_transform(df_new['preprocessed_text']).toarray()

## Creating tf-idf dataframe with sentiment

In [32]:
df_tfidf = pd.DataFrame(X_tfidf)
df_tfidf['sentiments'] = df_new['sentiment_label']
df_tfidf.head()

0    1    2    3    4    5    6    7    8    9  ...  7332  7333  7334  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   

   7335  7336  7337  7338  7339  7340  sentiments  
0   0.0   0.0   0.0   0.0   0.0   0.0     Neutral  
1   0.0   0.0   0.0   0.0   0.0   0.0     Neutral  
2   0.0   0.0   0.0   0.0   0.0   0.0     Neutral  
3   0.0   0.0   0.0   0.0   0.0   0.0     Neutral  
4   0.0   0.0   0.0   0.0   0.0   0.0     Neutral  

[5 rows x 7342 columns]

## Encoding the dependent feature

In [33]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df_tfidf["sentiments"] = encoder.fit_transform(df_tfidf["sentiments"])
df_tfidf.head()

0    1    2    3    4    5    6    7    8    9  ...  7332  7333  7334  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   

   7335  7336  7337  7338  7339  7340  sentiments  
0   0.0   0.0   0.0   0.0   0.0   0.0           1  
1   0.0   0.0   0.0   0.0   0.0   0.0           1  
2   0.0   0.0   0.0   0.0   0.0   0.0           1  
3   0.0   0.0   0.0   0.0   0.0   0.0           1  
4   0.0   0.0   0.0   0.0   0.0   0.0           1  

[5 rows x 7342 columns]

## Splitting into independent and dependent feature

In [36]:
X_tfidf = df_tfidf.iloc[:,:-1]
y_tfidf = df_tfidf.iloc[:,-1]

In [37]:
pd.DataFrame(X_tfidf)

0     1     2     3     4     5     6     7     8     9     ...  7331  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
3684   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3685   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3686   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3687   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3688   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      7332  7333  7334  7335  7336  7337  7338  7339  7340  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
3684   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3685   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3686   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3687   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3688   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[3689 rows x 7341 columns]

In [38]:
#pip install imbalanced-learn

In [39]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_tfidf, y_tfidf)

# Train test split

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [41]:
y_train.value_counts()

sentiments
2    1776
0    1775
1    1748
Name: count, dtype: int64

## Fitting Multinomial Naive Bayes Model

In [42]:
# Initialize and train the Multinomial Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier_NB = MultinomialNB()
classifier_NB.fit(X_train, y_train)

MultinomialNB()

## Making prediction on test set

In [44]:
y_pred_multinomial = classifier_NB.predict(X_test)

## Confusion Matrix, Accuracy, Precision and Recall and Cross validation

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
cm_nb_tf = confusion_matrix(y_test,y_pred_multinomial)
print(cm_nb_tf)
acc_nb_tf = accuracy_score(y_test,y_pred_multinomial)
print("The accuracy of naive bayes classifier using TFIDF is", acc_nb_tf)

precision_macro_nbtf = precision_score(y_test, y_pred_multinomial, average='macro')
print("The precision of naive bayes classifier using TFIDF is",precision_macro_nbtf)

recall_macro_nbtf = recall_score(y_test, y_pred_multinomial, average='macro')
print("The recall of naive bayes classifier using TFIDF is ",recall_macro_nbtf)

scores_nbtf = cross_val_score(classifier_NB,X_train,y_train,cv = 10, scoring = "accuracy")
print(scores_nbtf)
print("-------------------------------------------------------------")
print("The mean cross validation accuracy is", scores_nbtf.mean())

[[381  32  20]
 [ 99 269  92]
 [  3   4 425]]
The accuracy of naive bayes classifier using TFIDF is 0.8113207547169812
The precision of naive bayes classifier using TFIDF is 0.8207403269612342
The recall of naive bayes classifier using TFIDF is  0.8161621754130205
[0.81132075 0.78490566 0.81320755 0.78301887 0.80188679 0.81698113
 0.78301887 0.83773585 0.81886792 0.80340265]
-------------------------------------------------------------
The mean cross validation accuracy is 0.805434604272925


In [46]:
import tkinter as tk
from tkinter import ttk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import joblib

## TkInter user interface TF-IDF with multinomial NB

In [48]:
import tkinter as tk
import re
import string
import joblib
from textblob import TextBlob
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB


# Load the trained Naive Bayes classifier and TF-IDF vectorizer
classifier = joblib.load('naive_bayes_classifier.pkl')
cv = joblib.load('tfidf_cv.pkl')

label_mapping = {0: "negative", 1: "neutral", 2: "positive"}

def handle_emojis_with_lemmatizer1(text):
    # Convert emojis to their emotional descriptions
    for emoji_char, emoji_description in emojis_with_feelings:
        text = text.replace(emoji_char, " " + emoji_description)

    # Convert text to lowercase
    text = text.lower()

    # Remove hashtags using regex
    pattern = r'#\w+'
    text = re.sub(pattern, '', text)

    # Handle slang words using the custom slang dictionary
    words = word_tokenize(text)
    words_with_slang_replaced = [slang_dict[word] if word in slang_dict else word for word in words]
    text = " ".join(words_with_slang_replaced)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize the text into words
    words = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words("english"))
    words_without_stopwords = [word for word in words if word not in stop_words]

    # Lemmatize the tokens
    blob = TextBlob(" ".join(words_without_stopwords))
    lemmatized_words = [word.lemmatize() for word in blob.words]

    # Reconstruct the text with lemmatized words
    lemmatized_text_with_emojis = " ".join(lemmatized_words)
    for emoji_description, emoji_char in emojis_with_feelings:
        lemmatized_text_with_emojis = lemmatized_text_with_emojis.replace(emoji_description, emoji_char)

    return lemmatized_text_with_emojis

def classify_sentence():
    sentence = entry.get() 
    preprocessed_sentence = handle_emojis_with_lemmatizer1(sentence)
    sentence_vector = cv.transform([preprocessed_sentence])
    predicted_label_encoded = classifier.predict(sentence_vector)[0]

    # Get the corresponding text label using the mapping
    predicted_label_text = label_mapping[predicted_label_encoded]

    result_label.config(text=f'Predicted Label: {predicted_label_text}')

# Create the main window
root = tk.Tk()
root.title('Sentence Classifier')

# Create widgets
label = tk.Label(root, text='Enter a sentence:')
entry = tk.Entry(root, width=40)
classify_button = tk.Button(root, text='Classify', command=classify_sentence)
result_label = tk.Label(root, text='Predicted Label:')

# Layout the widgets
label.pack(pady=10)
entry.pack(pady=5)
classify_button.pack(pady=10)
result_label.pack(pady=10)

# Start the Tkinter event loop
root.mainloop()


## Bag of Words

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_bw = cv.fit_transform(df_new['preprocessed_text']).toarray()

In [61]:
df_bw = pd.DataFrame(X_bw)

In [62]:
df_bw['sentiments'] = df_new['sentiment_label']

## Creating a Bag of words dataframe

In [63]:
df_bw.head()

0  1  2  3  4  5  6  7  8  9  ...  7332  7333  7334  7335  7336  7337  \
0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

   7338  7339  7340  sentiments  
0     0     0     0     Neutral  
1     0     0     0     Neutral  
2     0     0     0     Neutral  
3     0     0     0     Neutral  
4     0     0     0     Neutral  

[5 rows x 7342 columns]

## Encoding the dependent Feature

In [64]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df_bw["sentiments"] = encoder.fit_transform(df_bw["sentiments"])

## Splitting into independent and dependent feature

In [65]:
X_bw = df_bw.iloc[:,:-1]
y_bw = df_bw.iloc[:,-1]

In [66]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled_bw, y_resampled_bw = smote.fit_resample(X_bw, y_bw)

## Train test split

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled_bw, y_resampled_bw, test_size=0.2, random_state=42)

## Multinomial NB model with BOW

In [68]:
# Initialize Multinomial Naive Bayes model
nb_model_bw = MultinomialNB()
nb_model_bw.fit(X_train, y_train)
y_pred_bw = nb_model_bw.predict(X_test)

## Confusion Matrix, Accuracy, Precision and Recall and Cross validation 

In [69]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

cm = confusion_matrix(y_test,y_pred_bw)
print(cm)
acc_bw = accuracy_score(y_test,y_pred_bw)
print("The accuracy of naive bayes classifier using bagofwords is", acc_bw)

precision_bw = precision_score(y_test, y_pred_bw, average='macro')
print("The precision of naive bayes classifier using bagofwords is",precision_bw)

recall_macro_bw = recall_score(y_test, y_pred_bw, average='macro')

print("The recall of naive bayes classifier using bagofwords is ",recall_macro_bw)

print("------------------------------------------------------------------------------------")
scores_nb_bw = cross_val_score(nb_model_bw,X_train,y_train,cv = 10, scoring = "accuracy")
print(scores_nb_bw)
print("-------------------------------------------------------------")
print("The mean cross validation accuracy is", scores_nb_bw.mean())


[[189  70 174]
 [101 280  79]
 [  7  22 403]]
The accuracy of naive bayes classifier using bagofwords is 0.6581132075471698
The precision of naive bayes classifier using bagofwords is 0.66779369223311
The recall of naive bayes classifier using bagofwords is  0.6593518766448612
------------------------------------------------------------------------------------
[0.6490566  0.57169811 0.61132075 0.58301887 0.56792453 0.59622642
 0.62264151 0.68679245 0.65849057 0.61814745]
-------------------------------------------------------------
The mean cross validation accuracy is 0.6165317259335878


## GloVe

In [6]:
preprocessed_texts = df_new['preprocessed_text'].tolist()

# Tokenize the sentences
sentence_tokens = [sent for sent in preprocessed_texts]

In [7]:
y = df_new['sentiment_label']

In [11]:
! pip install joblib

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [12]:
import numpy as np
from gensim.models import KeyedVectors
from nltk.tokenize import word_tokenize

# Load pre-trained Glove embeddings
glove_model = KeyedVectors.load_word2vec_format('glove.6B.100d.txt', binary=False)



sentence_vectors = []
y_gloved = []

index = 0
for sentence in sentence_tokens:
    tokens = word_tokenize(sentence.lower())  # Tokenize and convert to lowercase
    word_vectors = [glove_model[word] for word in tokens if word in glove_model]
    if word_vectors:
        sentence_vector = np.mean(word_vectors, axis=0)  # Calculate sentence vector by averaging word vectors
        sentence_vectors.append(sentence_vector)
        y_gloved.append(y[index])
        index = index + 1

sentence_vectors = np.array(sentence_vectors)

In [13]:
import joblib

In [14]:
joblib.dump(sentence_vectors, 'glove_sentence_vectors.pkl')
joblib.dump(y_gloved, 'labels.pkl')

['labels.pkl']

In [18]:
! pip install imblearn

  Obtaining dependency information for imbalanced-learn from https://files.pythonhosted.org/packages/a3/9e/fbe60a768502af54563dcb59ca7856f5a8833b3ad5ada658922e1ab09b7f/imbalanced_learn-0.11.0-py3-none-any.whl.metadata
Using cached imbalanced_learn-0.11.0-py3-none-any.whl (235 kB)


In [19]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(sentence_vectors_array, y)

## Test train split

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled, y_resampled, test_size = 0.20,random_state=42)

## Fitting and evaluating with Random Forest with GloVe

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:",accuracy)

cf_mat = confusion_matrix(y_test,y_pred)
cf_mat

Accuracy: 0.8173584905660377


array([[337,  90,   6],
       [ 99, 337,  24],
       [  7,  16, 409]], dtype=int64)

## Accuracy, Precision and Recall and Cross validation

In [23]:
cm_glove = confusion_matrix(y_test,y_pred)
print(cm_glove)
acc_glove = accuracy_score(y_test,y_pred)
print("The accuracy of Random Fores classifier using glove is", acc_glove)

precision_glove = precision_score(y_test, y_pred, average='macro')
print("The precision of Random Forest classifier using glove is",precision_glove)

recall_macro_glove = recall_score(y_test, y_pred, average='macro')
print("The recall of naive bayes classifier using glove is ",recall_macro_glove)

print("------------------------------------------------------------------------------------")
scores_rf_glv = cross_val_score(clf,X_train,y_train,cv = 10, scoring = "accuracy")
print(scores_rf_glv)
print("-------------------------------------------------------------")
print("The mean cross validation accuracy is", scores_rf_glv.mean())



[[337  90   6]
 [ 99 337  24]
 [  7  16 409]]
The accuracy of Random Fores classifier using glove is 0.8173584905660377
The precision of Random Forest classifier using glove is 0.817702521806349
The recall of naive bayes classifier using glove is  0.8192196493276755
------------------------------------------------------------------------------------


NameError: name 'cross_val_score' is not defined

In [24]:
joblib.dump(clf, 'random_forest_latest.pkl')
joblib.dump(glove_model, 'glove_model.pkl')

['glove_model.pkl']

## User Interface using TkInter for GloVe with Random Forest

In [25]:
import tkinter as tk
from tkinter import ttk
import joblib
import numpy as np

# Load the trained Random Forest classifier
classifier = joblib.load('random_forest_latest.pkl')
# Load the pre-trained Glove model from the pickle file
glove_model = joblib.load('glove_model.pkl')

label_mapping = {0: "negative", 1: "neutral", 2: "positive"}


def classify_sentence():
    sentence = entry.get()  # Get the input sentence
    
    # Preprocess the sentence using the provided function
    preprocessed_sentence = handle_emojis_with_lemmatizer1(sentence)
    
    # Using the loaded Glove model to transform the preprocessed sentence into a vector
    tokens = word_tokenize(preprocessed_sentence.lower()) 
    word_vectors = [glove_model[word] for word in tokens if word in glove_model]
    if word_vectors:
        sentence_vector = np.mean(word_vectors, axis=0) 

    # Using the trained Random Forest model to predict the label
    predicted_label_encoded = classifier.predict(sentence_vector.reshape(1, -1))
    print(predicted_label_encoded[0])
    # Get the corresponding text label using the mapping
    predicted_label_text = label_mapping[predicted_label_encoded[0]]
    
    result_label.config(text=f'Predicted Label: {predicted_label_text}')

# Creating the main window
root = tk.Tk()
root.title('Sentence Classifier using GloVe and Random Forest')

# Creating widgets
label = ttk.Label(root, text='Enter a sentence:')
entry = ttk.Entry(root, width=40)
classify_button = ttk.Button(root, text='Classify', command=classify_sentence)
result_label = ttk.Label(root, text='Predicted Label:')

# Layout the widgets
label.pack(pady=10)
entry.pack(pady=5)
classify_button.pack(pady=10)
result_label.pack(pady=10)

# Starting the Tkinter event loop
root.mainloop()

0
0
